#!/usr/bin/env python3
"""Embed the browser app + its ES modules into web_assets.h (PROGMEM) so the
ESP32 can serve the real, validated polygraph stack at http://192.168.4.1/.

Regenerate whenever polygraph_app.html / polygraph_engine.js /
polygraph_source.js / polygraph_synth.js change:

    python3 build_web_assets.py

Then rebuild/flash the .ino. Each asset is emitted as a raw string literal with
a delimiter guaranteed absent from the content.
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
DELIM = "POLY_ASSET_9c1f"           # raw-string delimiter; must not appear as )DELIM" in any file
ASSETS = [
    # (source file, C symbol, HTTP route, content-type)
    ("polygraph_app.html",    "APP_HTML",  "/",                     "text/html; charset=utf-8"),
    ("polygraph_engine.js",   "ENGINE_JS", "/polygraph_engine.js",  "text/javascript; charset=utf-8"),
    ("polygraph_source.js",   "SOURCE_JS", "/polygraph_source.js",  "text/javascript; charset=utf-8"),
    ("polygraph_synth.js",    "SYNTH_JS",  "/polygraph_synth.js",   "text/javascript; charset=utf-8"),
]

def main():
    close = ")" + DELIM + '"'
    out = []
    out.append("// AUTO-GENERATED by build_web_assets.py — do not edit by hand.")
    out.append("// Embeds the browser app + ES modules for the ESP32 to serve.")
    out.append("#pragma once")
    out.append("")
    routes = []
    for fname, sym, route, ctype in ASSETS:
        path = os.path.join(HERE, fname)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        if close in content:
            sys.exit(f"ERROR: raw-string delimiter collision in {fname}; pick a new DELIM")
        out.append(f'// {fname}  ({len(content.encode("utf-8"))} bytes)  -> {route}')
        out.append(f'static const char {sym}[] PROGMEM = R"{DELIM}(')
        out.append(content)
        out.append(f'){DELIM}";')
        out.append("")
        routes.append((sym, route, ctype))

    # Emit a small registration helper so the .ino stays declarative.
    out.append("// Register all asset routes on an AsyncWebServer instance.")
    out.append("#define REGISTER_WEB_ASSETS(server) do { \\")
    for sym, route, ctype in routes:
        out.append(f'  (server).on("{route}", HTTP_GET, [](AsyncWebServerRequest* r){{ '
                   f'r->send_P(200, "{ctype}", {sym}); }}); \\')
    out.append("} while (0)")
    out.append("")

    header = "\n".join(out)
    with open(os.path.join(HERE, "web_assets.h"), "w", encoding="utf-8") as f:
        f.write(header)
    total = sum(os.path.getsize(os.path.join(HERE, a[0])) for a in ASSETS)
    print(f"web_assets.h written: {len(ASSETS)} assets, ~{total//1024} KB of source embedded")
    for fname, sym, route, _ in ASSETS:
        print(f"  {route:<26} <- {fname} ({sym})")

if __name__ == "__main__":
    main()
